### ISSUE TITLE
Error in storybook when interacting with form controls

### ISSUE THREAD

**Issue by ksandin** [ksandin/yas#116]
Error: Storybook preview hooks can only be called inside decorators and story functions.
  at useStoryContext (/sb-preview/runtime.js:9:2119))
  at useParameter (/sb-preview/runtime.js:9:2226))
  at useThemeParameters (/node_modules/.cache/sb-vite/deps/@storybook_addon-themes.js?v=85aadd0d:27:46))
  at /node_modules/.cache/sb-vite/deps/@storybook_addon-themes.js?v=85aadd0d:35:27
  at hookified (/sb-preview/runtime.js:7:18973))
  at /sb-preview/runtime.js:41:1451
  at /sb-preview/runtime.js:41:1912
  at withOutline (/node_modules/.cache/sb-vite/deps/@storybook_addon-essentials_outline_preview.js?v=85aadd0d:441:43))
  at hookified (/sb-preview/runtime.js:7:18973))

**Comment by ksandin** [comment]
Seems to have been fixed. Cannot reproduce the issue.
